stages:
  - build
  - test

default:
  image: gcc:12

variables:
  BUILD_DIR: build

before_script:
  - apt-get update -qq && apt-get install -y -qq
    wget cmake g++
    libopenal-dev libflac-dev libvorbis-dev
    libudev-dev libxrandr-dev
    libfreetype6-dev libgl1-mesa-dev
  - wget -q https://www.sfml-dev.org/files/SFML-3.0.0-linux-gcc-64-bit.tar.gz
  - tar -xzf SFML-3.0.0-linux-gcc-64-bit.tar.gz
  - cd SFML-3.0.0
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF .
  - make -j$(nproc)
  - make install
  - ldconfig
  - cd $CI_PROJECT_DIR
build_job:
  stage: build
  script:
    - echo "Creating build directory..."
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - echo "Running CMake configuration..."
    - cmake .. -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DUSE_SFML=OFF
    - echo "Building the project..."
    - cmake --build .
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 1 week
  when: manual
  only:
    - merge_requests

test_job:
  stage: test
  dependencies:
    - build_job
  script:
    - echo "Running tests..."
    - cd $BUILD_DIR
    - ./tests/tests
  when: manual
  only:
    - merge_requests
